# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - loanapprovalplatform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://loanapproval.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5dba746576a14ec1aec2d8a27558aa8f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4b97504e5c97414396282d2c31888e28 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: loanapproval.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5dba746576a14ec1aec2d8a27558aa8f }}/loanapproval:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'loanapprovalplatform'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ceace23daca844e29e78348f05d31fa4 }}
        images: 'loanapproval.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5dba746576a14ec1aec2d8a27558aa8f }}/loanapproval:${{ github.sha }}'